### ISSUE TITLE
AttributeError: module 'pandas.core.computation' has no attribute 'expressions'

### ISSUE THREAD

**Issue by samiarja** [pkmital/tensorflow_tutorials#45]
I have followed basic_convnet.py and when I run the code I got the error below:
> C:\Users\Sami\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:/Users/Sami/GitHub-Repository/my_project_github_pycharm/ML_algorithms_libs/ConvNet.py", line 2, in <module>
    import tensorflow.examples.tutorials.mnist.input_data as input_data
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\examples\tutorials\mnist\__init__.py", line 21, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\examples\tutorials\mnist\input_data.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\__init__.py", line 31, in <module>
    from tensorflow.contrib import distributions
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\distributions\__init__.py", line 33, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\distributions\python\ops\estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\__init__.py", line 92, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\estimators\__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\estimators\dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\learn_io\__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "C:\Users\Sami\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\learn\python\learn\learn_io\dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "C:\Users\Sami\Anaconda3\lib\site-packages\dask\dataframe\__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "C:\Users\Sami\Anaconda3\lib\site-packages\dask\dataframe\core.py", line 41, in <module>
    pd.core.computation.expressions.set_use_numexpr(False)
**AttributeError: module 'pandas.core.computation' has no attribute 'expressions'**

# **Upgrading dask didn't help**, I would like to know how to fix this issue.

**Comment by Interstella12** [comment]
have you solved this problem?
I got the same error

**Comment by Interstella12** [comment]
I upgrade dask from 0.15.2 to 0.17.5 ,and it's solved
